[package]
name = "sotis-gui"
version.workspace = true
edition.workspace = true

[[bin]]
name = "sotis-gui"
path = "src/main.rs"

[features]
default = []
ocr = ["sotis-core/ocr"]

[dependencies]
sotis-core = { path = "../sotis-core" }
eframe = { workspace = true }
anyhow = { workspace = true }
